name: Prueba de tokens

on:
  push:

jobs:
  comparar:
    name: Comparar token
    runs-on: [self-hosted, Windows, X64]
    env:
      DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
    steps:
      - name: Comparar token
        shell: powershell
        run: |
          if ([string]::IsNullOrEmpty($env:DEV_TOKEN)) {
            Write-Error "DEV_TOKEN no está disponible."
            exit 1
          }
          if ([string]::IsNullOrEmpty($env:LOCAL_DEV_TOKEN)) {
            Write-Error "LOCAL_DEV_TOKEN no está disponible."
            exit 1
          }
          if ($env:DEV_TOKEN -ceq $env:LOCAL_DEV_TOKEN) {
            Write-Output "Los valores coinciden"
            exit 0
          }
          Write-Output "Los valores no coinciden"
          exit 1
